---
- hosts: localhost
  connection: local
  vars_files:
    - ./vars/vars.yml
  tasks:
    - name: "Remove resource group : {{ resourceGroupName }}"
      azure_rm_resourcegroup:
        name: "{{ resourceGroupName }}"
        force_delete_nonempty: yes
        state: absent
      register: rg
    - debug:
        var: rg